### PR TITLE
Fixed the 'new line' character inside double-quote causing the csv pa…

### PR DESCRIPTION
**Pull request by wwken**
A new line character should be allowed inside a double quote as a valid csv document.  For example, the following csv document should be treated as a SINGLE valid csv data

Iphone,"{ ItemName : Cheez-It
21 Ounce}",

However, the current implementation of the getNext() inside org.apache.pig.piggybank.storage.CSVLoader class fails to take care of this case and it sees two lines of data while in fact it should be treated as single line of data.

This pull request fixes the above issue.

(Note: here is a linke to validate whether a csv document:  http://csvlint.io/)

### CODE REVIEW

**Comment by catssifi** [comment]
unit-test

Screen shot of the new unit-test being added to the repo regrading to this fix

**Comment by wwken** [comment]
Screen shot of the new unit-test being added to the repo regrading to this fix

unit-test

**Comment by catssifi** [comment]
https://wwken.wordpress.com/2015/07/02/fixed-the-new-line-character-inside-double-quote-causing-the-csv-parsing-failure/

The related blog

**Comment by wwken** [comment]
https://wwken.wordpress.com/2015/07/02/fixed-the-new-line-character-inside-double-quote-causing-the-csv-parsing-failure/

The related blog

**Comment by wwken** [comment]
https://issues.apache.org/jira/browse/PIG-4623

the corresponding JIRA ticket

**Pull request closed without merging**
